# Generated by Django 3.2 on 2021-04-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('userid', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('body', models.TextField()),
            ],
            options={
                'db_table': 'jdata',
            },
        ),
    ]
